version: 2
jobs:
  llvm381:
    docker:
      - image: ponylang/ponyc-ci-llvm3.8.1
    steps:
      - checkout
      - run: make test-ci
  llvm391:
    docker:
      - image: ponylang/ponyc-ci-llvm3.9.1
    steps:
      - checkout
      - run: make test-ci

workflows:
  version: 2
  llvms:
    jobs:
      - llvm381
      - llvm391
